import { db } from "@/lib/db";
import { outfitters } from "@/lib/db/schema";

const SEED_OUTFITTERS = [
  {
    name: "Elk Ridge Outfitters",
    website: "https://elkridgeoutfitters.com",
    phone: "(307) 555-0101",
    email: "info@elkridgeoutfitters.com",
    stateCode: "WY",
    speciesSlugs: ["elk", "mule-deer"],
    unitCodes: ["WY-100", "WY-101"],
    huntTypes: ["rifle", "archery"],
    priceRange: "premium",
    description: "Premier guided elk hunts in the Bighorn Mountains. 90%+ opportunity rate on 6-point or better bulls.",
    verified: true,
  },
  {
    name: "Thunder Basin Hunts",
    website: "https://thunderbasinhunts.com",
    phone: "(307) 555-0202",
    email: "book@thunderbasinhunts.com",
    stateCode: "WY",
    speciesSlugs: ["antelope", "mule-deer"],
    unitCodes: ["WY-50", "WY-51"],
    huntTypes: ["rifle"],
    priceRange: "mid",
    description: "Quality antelope and mule deer hunts on private ranches in eastern Wyoming.",
    verified: true,
  },
  {
    name: "Rocky Mountain Trophy Hunts",
    website: "https://rmtrophyhunts.com",
    phone: "(303) 555-0301",
    email: "hunts@rmtrophyhunts.com",
    stateCode: "CO",
    speciesSlugs: ["elk", "mule-deer", "bear"],
    unitCodes: ["CO-61", "CO-62"],
    huntTypes: ["rifle", "archery", "muzzleloader"],
    priceRange: "premium",
    description: "Experienced guides leading hunts in GMU 61 and 62. Specializing in backcountry elk and trophy mule deer.",
    verified: true,
  },
  {
    name: "High Country Adventures",
    website: "https://highcountryadv.com",
    phone: "(303) 555-0302",
    stateCode: "CO",
    speciesSlugs: ["elk", "mule-deer"],
    unitCodes: ["CO-201", "CO-202"],
    huntTypes: ["archery"],
    priceRange: "mid",
    description: "Archery-focused outfitter in the Flat Tops Wilderness. Pack-in camps at 10,000+ ft.",
    verified: false,
  },
  {
    name: "Bitterroot Backcountry",
    website: "https://bitterrootbc.com",
    phone: "(406) 555-0401",
    email: "info@bitterrootbc.com",
    stateCode: "MT",
    speciesSlugs: ["elk", "whitetail", "bear"],
    unitCodes: ["MT-250", "MT-270"],
    huntTypes: ["rifle", "archery"],
    priceRange: "premium",
    description: "Wilderness pack trips in the Bitterroot-Selway. Mule and horse supported camps.",
    verified: true,
  },
  {
    name: "Missouri Breaks Outfitters",
    website: "https://missouribreaks.com",
    phone: "(406) 555-0402",
    stateCode: "MT",
    speciesSlugs: ["elk", "mule-deer", "antelope"],
    unitCodes: ["MT-410", "MT-411"],
    huntTypes: ["rifle"],
    priceRange: "mid",
    description: "Family-run operation in the Missouri Breaks. Great for first-time western hunters.",
    verified: true,
  },
  {
    name: "Salmon River Outfitters",
    website: "https://salmonriveroutfitters.com",
    phone: "(208) 555-0501",
    email: "book@salmonriveroutfitters.com",
    stateCode: "ID",
    speciesSlugs: ["elk", "mule-deer", "mountain-lion"],
    unitCodes: ["ID-20A", "ID-20"],
    huntTypes: ["rifle", "archery"],
    priceRange: "premium",
    description: "Deep wilderness hunts along the Middle Fork of the Salmon River. Fly-in base camp.",
    verified: true,
  },
  {
    name: "Clearwater Hunts",
    phone: "(208) 555-0502",
    stateCode: "ID",
    speciesSlugs: ["elk", "bear"],
    unitCodes: ["ID-10", "ID-12"],
    huntTypes: ["rifle"],
    priceRange: "budget",
    description: "No-frills guided elk hunts in the Clearwater region. OTC tag areas.",
    verified: false,
  },
  {
    name: "Gila Wilderness Outfitters",
    website: "https://gilawild.com",
    phone: "(575) 555-0601",
    email: "info@gilawild.com",
    stateCode: "NM",
    speciesSlugs: ["elk", "mule-deer", "coues-deer"],
    unitCodes: ["NM-16A", "NM-16B"],
    huntTypes: ["rifle", "archery", "muzzleloader"],
    priceRange: "mid",
    description: "Hunts in the Gila National Forest. Excellent draw odds for quality units.",
    verified: true,
  },
  {
    name: "Desert Canyon Hunts",
    website: "https://desertcanyonhunts.com",
    phone: "(575) 555-0602",
    stateCode: "NM",
    speciesSlugs: ["elk", "oryx", "barbary-sheep"],
    unitCodes: ["NM-34", "NM-36"],
    huntTypes: ["rifle"],
    priceRange: "luxury",
    description: "Trophy oryx on White Sands and premium elk in the Sacramento Mountains.",
    verified: true,
  },
  {
    name: "Kaibab Outfitters",
    website: "https://kaibaboutfitters.com",
    phone: "(928) 555-0701",
    email: "hunt@kaibaboutfitters.com",
    stateCode: "AZ",
    speciesSlugs: ["mule-deer", "elk", "coues-deer"],
    unitCodes: ["AZ-12AW", "AZ-13A"],
    huntTypes: ["rifle", "archery"],
    priceRange: "luxury",
    description: "Trophy mule deer on the Kaibab Plateau. 180\"+ bucks regularly taken.",
    verified: true,
  },
  {
    name: "Sonoran Desert Hunts",
    phone: "(520) 555-0702",
    email: "info@sonorandeserthunts.com",
    stateCode: "AZ",
    speciesSlugs: ["coues-deer", "javelina", "mule-deer"],
    unitCodes: ["AZ-33", "AZ-34A"],
    huntTypes: ["rifle", "archery"],
    priceRange: "mid",
    description: "Coues deer specialist in southern Arizona. January hunts with high success rates.",
    verified: false,
  },
  {
    name: "Book Cliffs Outfitters",
    website: "https://bookcliffshunts.com",
    phone: "(435) 555-0801",
    stateCode: "UT",
    speciesSlugs: ["elk", "mule-deer", "bison"],
    unitCodes: ["UT-BC-1", "UT-BC-2"],
    huntTypes: ["rifle", "archery", "muzzleloader"],
    priceRange: "premium",
    description: "Limited-entry hunts on the Book Cliffs. Known for giant bulls and heavy-horned deer.",
    verified: true,
  },
  {
    name: "Ruby Mountain Outfitters",
    website: "https://rubymountainhunts.com",
    phone: "(775) 555-0901",
    email: "info@rubymountainhunts.com",
    stateCode: "NV",
    speciesSlugs: ["mule-deer", "elk", "bighorn-sheep"],
    unitCodes: ["NV-061", "NV-062"],
    huntTypes: ["rifle"],
    priceRange: "luxury",
    description: "Once-in-a-lifetime Nevada hunts. Specializing in Ruby Mountain mule deer and desert bighorn.",
    verified: true,
  },
  {
    name: "Steens Mountain Hunts",
    website: "https://steensmountainhunts.com",
    phone: "(541) 555-1001",
    stateCode: "OR",
    speciesSlugs: ["mule-deer", "antelope", "elk"],
    unitCodes: ["OR-STN", "OR-WHT"],
    huntTypes: ["rifle", "archery"],
    priceRange: "mid",
    description: "Eastern Oregon hunts in the Steens Mountain and Whitehorse units. Great public land access.",
    verified: true,
  },
  {
    name: "Yellowstone Country Outfitters",
    website: "https://yellowstonecountry.com",
    phone: "(406) 555-0403",
    email: "info@yellowstonecountry.com",
    stateCode: "MT",
    speciesSlugs: ["elk", "moose", "bighorn-sheep"],
    unitCodes: ["MT-301", "MT-313"],
    huntTypes: ["rifle", "archery"],
    priceRange: "luxury",
    description: "Exclusive guided hunts bordering Yellowstone. Trophy bull elk and rare moose permits.",
    verified: true,
  },
];

export async function seedOutfitters() {
  console.log("Seeding outfitters...");

  for (const o of SEED_OUTFITTERS) {
    await db
      .insert(outfitters)
      .values(o)
      .onConflictDoNothing();
  }

  console.log(`Seeded ${SEED_OUTFITTERS.length} outfitters.`);
}
